### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by SaqibYT** [bluecantcode/ticket-bot#1]
Can You Please Add Reactions? so you do -new and it will show you a list of reactions 
You will pick an emoji for a topic like apply for staff and technical support and you will react on it to make it. Same for closing please. Also when I do -new on my alt it shows only 2cmds how to fix?

**Comment by SaqibYT** [comment]
The alt has no perm

**Comment by ifisq** [comment]
Unfortunately, I'm not actively maintaining this repository anymore so I'm not adding new features. Sorry about that. In regards to your alt only seeing 2 commands, that's because it doesn't have sufficient permissions to use the bot, as you mentioned. They'll need to either have administrator permissions for the server, or they'll need to have a bot-verified role. You can do this by running `.addadminrole <role_id>`

**Comment by SaqibYT** [comment]
but i have added new commands so how can i add them to the embeds so useres can see that aswell#

**Comment by ifisq** [comment]
You have to add them to the .help command’s embed. Please refrain from editing the bot’s code if you don’t know python and don’t have experience with discord.py, as you could mess up other stuff with the bot.

**Comment by SaqibYT** [comment]
i know py pretty well. the thing is it doesnt show on my screen

**Comment by SaqibYT** [comment]
so like say they dont have admin perm it just shows .new an .close

**Comment by ifisq** [comment]
You have to add a field to the help embed here, as I mentioned earlier: https://github.com/ifisq/discord-ticket-system/blob/master/main.py#L48

**Comment by SaqibYT** [comment]
thanks. also if i add this on more than 1 server and say on thr config.json the people that have access to tickets in my server will they have access to it if i put it in a different server?

**Comment by SaqibYT** [comment]
like if the bot is in more than 1 server

**Comment by SaqibYT** [comment]
and the people who have access in my server will they have accss to it in the other server that has the bot?

**Comment by ifisq** [comment]
The bot is meant for use in only one server.

**Comment by SaqibYT** [comment]
ok
